# Generated by Django 6.0 on 2025-12-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0003_alter_arquivoobra_arquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArquivoObra',
            new_name='Arquivo',
        ),
    ]
