# Generated by Django 6.0 on 2025-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0004_rename_arquivoobra_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
