# Generated by Django 6.0 on 2025-12-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0005_arquivo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='nome',
        ),
    ]
