# Generated by Django 6.0 on 2025-12-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0006_remove_arquivo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='descricao',
        ),
    ]
