# Generated by Django 6.0 on 2025-12-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proacademico', '0007_remove_arquivo_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
    ]
